### ISSUE TITLE
Live preview link doesn't work

### ISSUE THREAD

**Issue by srxcode** [darshanC07/web-scraper#1]
The live preview link provided in the README file doesn't work (https://darshanc07.github.io/web-scraper/) . Just a guess, github hosting only allows static website hosting, and tasks like web scraping probably require a proper backend, so you probably need to host it somewhere else...

**Comment by darshanC07** [comment]
You are right...initially, I didn't host the server.. but NOW, I have done it...
So now you can have a preview on the link : [https://darshanc07.github.io/web-scraper/](https://darshanc07.github.io/web-scraper/)
